### ISSUE TITLE
Resource Hacker hashing error

### ISSUE THREAD

**Issue by sw1ndl3d** [mandiant/commando-vm#307] opened 2023-09-09 03:02 UTC
**Describe the bug and expected behavior**
When beginning the base install of commando, I specifically was receiving and error for the Resource Hacker package from chocolatey. At first glance, it says that it was a mismatch in hashes. While this may be true, I believe the issue stems from the package name that is being referenced somewhere? I tried looking through files on both `VM-Packages` and the `commando-vm` but wasn't successful in seeing where the error may have stemmed from.

**To Reproduce**
1. Base install of commando
2. See error
![resource_hacker_error](https://github.com/mandiant/commando-vm/assets/81738199/8e085dac-83b4-40a4-997b-aeb7bf689812)
![choco_reshack_install](https://github.com/mandiant/commando-vm/assets/81738199/6235bc86-fcf2-41fe-bbaf-9ce82fb83887)

**Version**
 - OS: Win10 22H2 OS-Build: 19045.2965

**Comment by sw1ndl3d** [comment] 2023-09-09 03:24
Not sure if this is the issue, but the chocolateyInstall.ps1 that is provided for Resource Hacker includes a cmdlet that does not appear to exist by default? Perhaps this is breaking the install process because it isn't unzipping the zip file, resulting in no `.exe` being available to run?
![resource_hacker_choco_install](https://github.com/mandiant/commando-vm/assets/81738199/b1d92c96-9036-4fe0-9d23-cf155f56c9c2)

**Comment by day1player** [comment] 2023-10-12 17:42
@sw1ndl3d This issue snuck by me here, sorry for the delay.. the source code for this package is located here: https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/reshack

It is not maintained by us. 

It looks like you maybe didnt run your install command in an admin prompt? I was not able to reproduce:
<img width="536" alt="image" src="https://github.com/mandiant/commando-vm/assets/37482972/03877502-7dc1-4fe4-8229-212ff6fdc79b">


The `Install-ChocolateyZipPackage` function is a part of the Chocolatey suite: https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage#mainContent

I am going to close this issue since I am not able to reproduce. Please let me know if you need anymore help!

**Closed by day1player** 2023-10-12 17:42 UTC
